version: '3.4'

services:
  botgpt:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=abc
      - OPENAI_API_KEY=xyz
      - OPENAI_API_BASE=https://api.chatanywhere.cn/v1
    